name: Deploy Hexo site to GitHub Pages

on:
  push:
    branches:
      - release

  # Allows you to run this workflow manually from the Actions tab
  # 可以手动触发
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'
        required: true
        default: 'warning'
      tags:
        description: 'Test scenario tags'

jobs:
  build-deploy:
    runs-on: ubuntu-22.04
    permissions:
      contents: write
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}

    steps:
    - name: Checkout source code
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '24'

    - name: Cache dependencies
      uses: actions/cache@v4
      with:
        path: ~/.npm
        key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-node-

    - name: Install dependencies
      run: npm ci

    - name: Clone Hexo theme and install theme dependencies
      run: |
        git clone https://github.com/probberechts/hexo-theme-cactus.git themes/cactus
        cd themes/cactus
        npm install

    - name: Build Hexo
      run: npm run build

    - name: Add CNAME file
      run: echo ${{ secrets.HEXO_CNAME }} > ./public/CNAME

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v4
      if: github.ref == 'refs/heads/release'
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./public
      
