name: Deploy Hexo site to GitHub Pages

on:
  push:
    branches:
      - gh-pages

  # Allows you to run this workflow manually from the Actions tab
  # 可以手动触发
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'
        required: true
        default: 'warning'
      tags:
        description: 'Test scenario tags'

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout source code
      uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'  # 使用合适的 Node.js 版本

    - name: Install dependencies
      run: npm install

    - name: Clone Hexo theme and install theme dependencies
      run: |
        git clone https://github.com/probberechts/hexo-theme-cactus.git themes/cactus
        cd themes/cactus
        npm install

    - name: Build Hexo
      run: npm run build

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.HEXO_DEPLOY_TOKEN }}
        publish_dir: ./public
